name: run-tests
on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # load cached env (otherwise nerfstudio can take quite long to install)
    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

    # checkout seathru-nerf (this repo)
    - uses: actions/checkout@v3
      with:
        path: seathru_nerf

    - name: Install seathru
      working-directory: ./seathru_nerf
      run: |
        pip install -e .

    # Run tests
    - name: run tests
      working-directory: ./seathru_nerf
      run: pytest ./tests
